kind: job
metadata:
  name: train-valid-test-splitter
  hash: 030843942525017287b28338ea48b1eed3955df3
  project: default
spec:
  command: /User/repos/demos/dask/code/train-valid-test-splitter.py
  args: []
  image: yjbds/mlrun-dask:dev
  volumes: []
  volume_mounts: []
  env: []
  description: ''
  build:
    image: yjbds/mlrun-dask:dev
    commands: []
