kind: job
metadata:
  name: train-valid-test-splitter-airlines
  hash: b2c73e59275fd00576068e1aa2e71b7a8b2ed393
  project: default
spec:
  command: /User/repos/demos/dask/code/train-valid-test-splitter-airlines.py
  args: []
  image: yjbds/mlrun-dask:dev
  volumes: []
  volume_mounts: []
  env: []
  description: ''
  build:
    image: yjbds/mlrun-dask:dev
    commands: []
